behaviors:
  TicTacToe:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 64
      num_layers: 8
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    self_play:
      save_steps: 10000
      swap_steps: 10000
      play_against_current_self_ratio: 0.5
      window: 5
    max_steps: 2000000
    time_horizon: 64
    summary_freq: 10000